# StatsLibX — Complete API Reference

A comprehensive guide covering **every** public method in the library.

---
**Author:** Emmanuel Ascendra  
**Version:** 0.2.9  
**License:** MIT

## API Index (v0.2.9)

| Module / Class | Public methods & attributes |
|---|---|
| **Package** | `__version__`, `__author__`, `welcome()`, `logger` |
| **datasets** | `load_dataset`, `load_iris`, `load_penguins`, `generate_dataset` |
| **DescriptiveStats** | `from_file`, `backend`, `data`, `lang`, `mean`, `median`, `mode`, `variance`, `std`, `skewness`, `kurtosis`, `quantile`, `outliers`, `correlation`, `covariance`, `summary`, `linear_regression`, `help` |
| **DescriptiveSummary** | `to_dataframe`, `to_styled_df`, `to_categorical_summary`, `results` |
| **LinearRegressionResult** | `fit`, `predict`, `summary`, `plot`, `coef_`, `intercept_`, `r_squared`, `p_values` |
| **InferentialStats** | `from_file`, `backend`, `numeric_columns`, `categorical_columns`, `confidence_interval`, `t_test_1sample`, `t_test_2sample`, `t_test_paired`, `mann_whitney_test`, `chi_square_test`, `anova_oneway`, `kruskal_wallis_test`, `normality_test`, `hypothesis_test`, `variance_test`, `help` |
| **TestResult** | `test_name`, `statistic`, `pvalue`, `alpha`, `interpretation`, `params`, `additional_params`, `homo_result` |
| **Preprocessing** | `backend`, `data`, `columns`, `detect_nulls`, `check_uniqueness`, `preview_data`, `describe_numeric`, `describe_categorical`, `fill_nulls`, `normalize`, `standardize`, `filter_rows`, `filter_columns`, `rename_columns`, `detect_outliers`, `data_quality`, `change_dtypes`, `clean_data` |
| **ComputationalStats** | `backend`, `regression`, `linear_regression`, `polynomial_regression`, `find_best_degree`, `interpolation`, `bootstrapping`, `k_means`, `elbow_method`, `correlation_analysis`, `plot_correlation_heatmap`, `descriptive_statistics`, `plot_distribution`, `help` |
| **RegressionResult** | `summary`, `plot`, `predict`, `get_formula` |
| **InterpolationResult** | `summary`, `plot`, `predict` |
| **BootstrappingResult** | `summary`, `plot`, `original_stat`, `std_error`, `percentile_ci` |
| **UtilsStats** | `load_data`, `validate_dataframe`, `format_number`, `check_normality`, `calculate_confidence_intervals`, `detect_outliers`, `calculate_effect_size`, `plot_distribution`, `plot_correlation_matrix`, `plot_scatter_matrix`, `plot_distribution_with_ci`, `get_descriptive_stats`, `set_plot_backend`, `set_default_figsize`, `set_save_fig_options`, `help` |
| **Backend** | `type`, `df`, `to_pandas`, `is_pandas`, `is_polars`, `shape`, `columns`, `numeric_columns`, `categorical_columns`, `col`, `col_numpy`, `mean`, `median`, `std`, `corr`, `cov`, `copy` |
| **viewx** | `HTML`, `Slides`, `Report`, `DataMatrix`, `to_report_data` |

In [1]:
import statslibx as slx
from statslibx.datasets import load_dataset, load_iris, load_penguins, generate_dataset
from statslibx import DescriptiveStats, InferentialStats, ComputationalStats, UtilsStats, Preprocessing
import pandas as pd
import numpy as np

print(f"StatsLibX v{slx.__version__}")
slx.welcome()

StatsLibX v0.2.9
StatsLibx v0.2.9
Descriptive and inferential statistics library
Author: Emmanuel Ascendra

Classes:
  - DescriptiveStats   Descriptive statistics
  - InferentialStats   Inferential statistics
  - ComputationalStats Computational statistics
  - UtilsStats         Utilities and visualization
  - Preprocessing      Data preparation

Modules:
  - datasets           Built-in datasets and generators

Docs: https://ghostanalyst30.github.io/StatsLibX/

---
## 1. Datasets

Built-in dataset loading and synthetic data generation.

### load_dataset
Load any built-in dataset by name. Supports CSV, Excel, Parquet, JSON.

In [2]:
iris = load_dataset("iris.csv")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df = load_dataset("penguins.csv")
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")

Shape: (344, 7)
Columns: ['species', 'island', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g', 'sex']

### load_iris / load_penguins
Convenience shortcuts for the two most common datasets.

In [4]:
iris2 = load_iris()
penguins2 = load_penguins()
print(f"Iris: {iris2.shape}, Penguins: {penguins2.shape}")

Iris: (150, 5), Penguins: (344, 7)

### from_file
Load data directly into `DescriptiveStats` or `InferentialStats`.

In [ ]:
ds_file = DescriptiveStats.from_file("iris.csv")
print(f"Loaded via from_file: {ds_file.data.shape}")

inf_file = InferentialStats.from_file("iris.csv")
print(inf_file.t_test_1sample("sepal_length", popmean=5.8))

### load_dataset with polars backend
Requires `pip install polars`.

In [ ]:
try:
    import polars as pl
    iris_pl = load_dataset("iris.csv", backend="polars")
    print(f"Polars dataset type: {type(iris_pl).__name__}, rows={iris_pl.height}")
except ImportError:
    print("Polars not installed")

### generate_dataset
Generate synthetic data with configurable distributions.

In [5]:
schema = {
    "age":     {"dist": "normal", "mean": 35, "std": 10, "type": "int"},
    "income":  {"dist": "lognormal", "mean": 10, "std": 1, "round": 0},
    "group":   {"dist": "categorical", "choices": ["A", "B", "C"]},
    "score":   {"dist": "uniform", "low": 0, "high": 100, "round": 1},
    "errors":  {"dist": "exponential", "scale": 1, "round": 3},
    "events":  {"dist": "poisson", "lam": 3, "type": "int"},
    "success": {"dist": "binomial", "n": 10, "p": 0.5, "type": "int"},
}
synth = generate_dataset(1000, schema, seed=42)
synth.head()

   age        income group  score  errors  events  success
0   38  20758.630232     C   37.5   0.718       1        4
1   25  10622.323579     A   97.0   0.461      10        8
2   43  14552.628863     B   17.3   2.002       3        4
3   44  41519.163791     B   32.0   2.202       3        5
4   15  22092.496196     C   29.4   0.968       6        6

---
## 2. DescriptiveStats

Descriptive statistics, correlations, regressions, outlier detection.

In [6]:
ds = DescriptiveStats(iris)
print(f"Backend: {ds.backend}")

Backend: pandas

### summary
Full descriptive summary across all or selected columns.

In [7]:
ds.summary()

====================================================================================================
                                 RESUMEN DE ESTADÍSTICA DESCRIPTIVA
====================================================================================================
Fecha: 2026-05-31 00:16:28
Variables analizadas: 4
----------------------------------------------------------------------------------------------------

                                       VARIABLE: sepal_length
----------------------------------------------------------------------------------------------------

Medidas de Tendencia Central:
  Conteo                                                  150
  Media                                              5.843333
  Mediana                                            5.800000
  Moda                                               5.000000

Medidas de Dispersión:
  Desviación Estándar                                0.828066
  Varianza                                           0.685694
  Rango Intercuartílico (IQR)                        1.300000

Cuartiles y Rango:
  Mínimo                                             4.300000
  Primer Cuartil (Q1)                                5.100000
  Tercer Cuartil (Q3)                                6.400000
  Máximo                                             7.900000

Forma de la Distribución:
  Asimetría (Skewness)                               0.314911
  Curtosis (Kurtosis)                               -0.552064
----------------------------------------------------------------------------------------------------

                                       VARIABLE: sepal_width
----------------------------------------------------------------------------------------------------

Medidas de Tendencia Central:
  Conteo                                                  150
  Media                                              3.054000
  Mediana                                            3.000000
  Moda                                               3.000000

Medidas de Dispersión:
  Desviación Estándar                                0.433594
  Varianza                                           0.188004
  Rango Intercuartílico (IQR)                        0.500000

Cuartiles y Rango:
  Mínimo                                             2.000000
  Primer Cuartil (Q1)                                2.800000
  Tercer Cuartil (Q3)                                3.300000
  Máximo                                             4.400000

Forma de la Distribución:
  Asimetría (Skewness)                               0.334053
  Curtosis (Kurtosis)                                0.290781
----------------------------------------------------------------------------------------------------

                                       VARIABLE: petal_length
----------------------------------------------------------------------------------------------------

Medidas de Tendencia Central:
  Conteo                                                  150
  Media                                              3.758667
  Mediana                                            4.350000
  Moda                                               1.500000

Medidas de Dispersión:
  Desviación Estándar                                1.764420
  Varianza                                           3.113179
  Rango Intercuartílico (IQR)                        3.500000

Cuartiles y Rango:
  Mínimo                                             1.000000
  Primer Cuartil (Q1)                                1.600000
  Tercer Cuartil (Q3)                                5.100000
  Máximo                                             6.900000

Forma de la Distribución:
  Asimetría (Skewness)                              -0.274464
  Curtosis (Kurtosis)                               -1.401921
----------------------------------------------------------------------------------------------------

                                       VARIABLE: petal_width
----------------------------------------------------------------------------------------------------

Medidas de Tendencia Central:
  Conteo                                                  150
  Media                                              1.198667
  Mediana                                            1.300000
  Moda                                               0.200000

Medidas de Dispersión:
  Desviación Estándar                                0.763161
  Varianza                                           0.582414
  Rango Intercuartílico (IQR)                        1.500000

Cuartiles y Rango:
  Mínimo                                             0.100000
  Primer Cuartil (Q1)                                0.300000
  Tercer Cuartil (Q3)                                1.800000
  Máximo                                             2.500000

Forma de la Distribución:
  Asimetría (Skewness)                              -0.104997
  Curtosis (Kurtosis)                               -1.339754
----------------------------------------------------------------------------------------------------
====================================================================================================

In [8]:
ds.summary(columns=["sepal_length", "petal_length"])

====================================================================================================
                                 RESUMEN DE ESTADÍSTICA DESCRIPTIVA
====================================================================================================
Fecha: 2026-05-31 00:16:28
Variables analizadas: 2
----------------------------------------------------------------------------------------------------

                                       VARIABLE: sepal_length
----------------------------------------------------------------------------------------------------

Medidas de Tendencia Central:
  Conteo                                                  150
  Media                                              5.843333
  Mediana                                            5.800000
  Moda                                               5.000000

Medidas de Dispersión:
  Desviación Estándar                                0.828066
  Varianza                                           0.685694
  Rango Intercuartílico (IQR)                        1.300000

Cuartiles y Rango:
  Mínimo                                             4.300000
  Primer Cuartil (Q1)                                5.100000
  Tercer Cuartil (Q3)                                6.400000
  Máximo                                             7.900000

Forma de la Distribución:
  Asimetría (Skewness)                               0.314911
  Curtosis (Kurtosis)                               -0.552064
----------------------------------------------------------------------------------------------------

                                       VARIABLE: petal_length
----------------------------------------------------------------------------------------------------

Medidas de Tendencia Central:
  Conteo                                                  150
  Media                                              3.758667
  Mediana                                            4.350000
  Moda                                               1.500000

Medidas de Dispersión:
  Desviación Estándar                                1.764420
  Varianza                                           3.113179
  Rango Intercuartílico (IQR)                        3.500000

Cuartiles y Rango:
  Mínimo                                             1.000000
  Primer Cuartil (Q1)                                1.600000
  Tercer Cuartil (Q3)                                5.100000
  Máximo                                             6.900000

Forma de la Distribución:
  Asimetría (Skewness)                              -0.274464
  Curtosis (Kurtosis)                               -1.401921
----------------------------------------------------------------------------------------------------
====================================================================================================

### DescriptiveSummary (result of `summary()`)
Methods: `to_dataframe`, `to_styled_df`, `to_categorical_summary`.

In [ ]:
summary_obj = ds.summary(columns=["sepal_length"])
summary_obj.to_dataframe(format="wide")

In [ ]:
summary_obj.to_dataframe(format="compact")

In [ ]:
# summary_obj.to_styled_df()  # styled pandas Styler
summary_obj.to_categorical_summary() if hasattr(summary_obj, 'to_categorical_summary') else None

### Central tendency

In [9]:
print(f"Mean:     {ds.mean('sepal_length'):.4f}")
print(f"Median:   {ds.median('sepal_length'):.4f}")
print(f"Mode:     {ds.mode('sepal_length')}")

Mean:     5.8433
Median:   5.8000
Mode:     5.0

### Dispersion

In [10]:
print(f"Std dev:  {ds.std('sepal_length'):.4f}")
print(f"Variance: {ds.variance('sepal_length'):.4f}")
print(f"Quantile(0.25): {ds.quantile(0.25, 'sepal_length'):.4f}")

Std dev:  0.8281
Variance: 0.6857
Quantile(0.25): 5.1000

### Shape

In [11]:
print(f"Skewness: {ds.skewness('sepal_length'):.4f}")
print(f"Kurtosis: {ds.kurtosis('sepal_length'):.4f}")

Skewness: 0.3149
Kurtosis: -0.5521

### Correlation & Covariance

In [12]:
ds.correlation(method="pearson")

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

In [13]:
ds.covariance()

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      0.685694    -0.039268      1.273682     0.516904
sepal_width      -0.039268     0.188004     -0.321713    -0.117981
petal_length      1.273682    -0.321713      3.113179     1.296387
petal_width       0.516904    -0.117981      1.296387     0.582414

In [14]:
ds.correlation(method="spearman", columns=["sepal_length", "sepal_width", "petal_length"])

              sepal_length  sepal_width  petal_length
sepal_length      1.000000    -0.159457      0.881386
sepal_width      -0.159457     1.000000     -0.303421
petal_length      0.881386    -0.303421      1.000000

### Linear Regression

In [15]:
result = ds.linear_regression("sepal_length", "petal_length", engine="statsmodels")
print(result)

====================================================================================================
                                   RESULTADOS DE REGRESIÓN LINEAL
====================================================================================================
Variable Dependiente: petal_length
Variables Independientes: sepal_length
Motor: statsmodels
Fecha: 2026-05-31 00:16:37
----------------------------------------------------------------------------------------------------

INFORMACIÓN DEL MODELO:
----------------------------------------------------------------------------------------------------
Estadístico                                                       Valor
----------------------------------------------------------------------------------------------------
R-cuadrado                                                     0.759955
R-cuadrado Ajustado                                            0.758333
Estadístico F                                                468.551862
Prob (F-estadístico)                                       1.038454e-47
AIC                                                          384.985365
BIC                                                          391.006636

COEFICIENTES:
----------------------------------------------------------------------------------------------------
Variable                       Coef.         Std Err               t           P>|t|
----------------------------------------------------------------------------------------------------
const                      -7.095381               -               -               -
sepal_length                1.857510        0.085813          21.646        0.000000

ANÁLISIS DE RESIDUOS:
----------------------------------------------------------------------------------------------------
Estadístico                                                       Valor
----------------------------------------------------------------------------------------------------
Media de Residuos                                              0.000000
Desv. Std. de Residuos                                         0.861580
Mínimo Residuo                                                -2.478175
Máximo Residuo                                                 2.493584
====================================================================================================

In [16]:
result2 = ds.linear_regression(
    X=["sepal_length", "sepal_width"],
    y="petal_length",
    engine="scikit-learn"
)
print(f"Coefficients: {result2.coef_}")
print(f"R-squared: {result2.r_squared:.4f}")
print(f"Intercept: {result2.intercept_:.4f}")

Coefficients: [ 1.78081362 -1.33924232]
R-squared: 0.8670
Intercept: -2.5572

### LinearRegressionResult attributes
After `linear_regression()`: `predict`, `plot`, `coef_`, `intercept_`, `r_squared`, `p_values`.

In [ ]:
pred = result.predict(iris[["sepal_length"]].head())
print(f"Predictions: {pred}")
print(f"Coef: {result.coef_}, Intercept: {result.intercept_:.4f}, R2: {result.r_squared:.4f}")
# result.plot()  # uncomment to display regression plot

### Outlier Detection

In [17]:
outliers_iqr = ds.outliers("sepal_length", method="iqr", threshold=1.5)
print(f"IQR outliers: {outliers_iqr.sum()} / {len(outliers_iqr)}")

IQR outliers: 0 / 150

In [18]:
outliers_z = ds.outliers("sepal_length", method="zscore", threshold=2)
print(f"Z-score outliers: {outliers_z.sum()} / {len(outliers_z)}")

Z-score outliers: 6 / 150

### help
Display detailed documentation.

In [19]:
# ds.help()  # uncomment to display

---
## 3. InferentialStats

Hypothesis testing, confidence intervals, normality tests, ANOVA, chi-square.

In [20]:
inf = InferentialStats(iris)
print(f"Backend: {inf.backend}")
print(f"Numeric cols: {inf.numeric_columns()}")
print(f"Categorical cols: {inf.categorical_columns()}")

Backend: pandas
Numeric cols: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
Categorical cols: ['species']

### Confidence Intervals

In [21]:
ci_mean = inf.confidence_interval("sepal_length", confidence=0.95, statistic="mean")
print(f"CI mean: {ci_mean}")

CI mean: (5.709732481507366, 5.976934185159301, 5.843333333333334)

In [22]:
ci_median = inf.confidence_interval("sepal_length", confidence=0.95, statistic="median")
print(f"CI median: {ci_median}")

CI median: (5.6, 6.0, 5.8)

### T-Tests

In [23]:
# One-sample t-test
t1 = inf.t_test_1sample("sepal_length", popmean=5.8, alternative="two-sided")
print(f"T-test 1sample: p={t1.pvalue:.4f}, stat={t1.statistic:.4f}")

T-test 1sample: p=0.5226, stat=0.6409

In [24]:
# One-sample median (Wilcoxon signed-rank)
t1m = inf.t_test_1sample("sepal_length", popmedian=5.0)
print(f"Wilcoxon: p={t1m.pvalue:.4f}")

Wilcoxon: p=0.0000

In [25]:
# Two-sample independent t-test
t2 = inf.t_test_2sample("sepal_length", "petal_length", equal_var=True)
print(f"T-test 2sample: p={t2.pvalue:.4f}")

T-test 2sample: p=0.0000

In [26]:
# Paired t-test
tp = inf.t_test_paired("sepal_length", "petal_length")
print(f"Paired t-test: p={tp.pvalue:.4f}")

Paired t-test: p=0.0000

### Normality Tests

In [27]:
n1 = inf.normality_test("sepal_length", method="shapiro")
print(f"Shapiro-Wilk: stat={n1.statistic:.4f}, p={n1.pvalue:.4f}")

Shapiro-Wilk: stat=0.9761, p=0.0102

In [28]:
n2 = inf.normality_test("sepal_length", method="anderson")
print(f"Anderson-Darling: stat={n2.statistic:.4f}, normal={n2.additional_params.get('normal', '?')}")

AttributeError: 'TestResult' object has no attribute 'additional_params'

In [29]:
n3 = inf.normality_test("sepal_length", method="all")
print(type(n3))  # dict with all tests

<class 'dict'>

### ANOVA

In [30]:
aov = inf.anova_oneway("sepal_length", "species")
print(f"ANOVA: F={aov.statistic:.4f}, p={aov.pvalue:.6f}")

ANOVA: F=119.2645, p=0.000000

### Non-parametric Tests

In [31]:
mw = inf.mann_whitney_test("sepal_length", "petal_length")
print(f"Mann-Whitney U: stat={mw.statistic:.1f}, p={mw.pvalue:.4f}")

Mann-Whitney U: stat=19249.0, p=0.0000

In [32]:
kw = inf.kruskal_wallis_test("sepal_length", "species")
print(f"Kruskal-Wallis: H={kw.statistic:.4f}, p={kw.pvalue:.6f}")

Kruskal-Wallis: H=96.9374, p=0.000000

### Chi-Square Test

In [36]:
cs_test = inf.chi_square_test("species", "species")  # use two categorical columns
print(f"Chi-square: stat={cs_test.statistic:.4f}, p={cs_test.pvalue:.4f}")

Chi-square: stat=300.0000, p=0.0000

### Variance Tests

In [37]:
vt = inf.variance_test("sepal_length", "petal_length", method="levene")
print(f"Levene: stat={vt.statistic:.4f}, p={vt.pvalue:.4f}")

Levene: stat=66.6739, p=0.0000

In [38]:
vt2 = inf.variance_test("sepal_length", "petal_length", method="bartlett")
print(f"Bartlett: stat={vt2.statistic:.4f}, p={vt2.pvalue:.4f}")

Bartlett: stat=77.9329, p=0.0000

In [39]:
vt3 = inf.variance_test("sepal_length", "petal_length", method="var_test")
print(f"F-test: stat={vt3.statistic:.4f}, p={vt3.pvalue:.4f}")

F-test: stat=0.2203, p=0.0000

### Hypothesis Test (unified interface)

In [40]:
# Test for mean
ht = inf.hypothesis_test(method="mean", column1="sepal_length", pop_mean=5.8)
print(ht)
print(f"Test: {ht.test_name}, statistic={ht.statistic:.4f}, p={ht.pvalue:.4f}")

In [41]:
# Test for difference of means
ht2 = inf.hypothesis_test(
    method="difference_mean",
    column1="sepal_length",
    column2="petal_length",
    homoscedasticity="levene"
)
print(ht2)
if ht2.homo_result:
    print(f"Homoscedasticity: equal_var={ht2.homo_result['equal_var']}")

### TestResult attributes
All inferential tests return `TestResult` with: `test_name`, `statistic`, `pvalue`, `alpha`, `interpretation`, `params`, `additional_params`, `homo_result`.

In [ ]:
t1 = inf.t_test_1sample("sepal_length", popmean=5.8)
print(f"Attributes: test_name={t1.test_name}, pvalue={t1.pvalue:.4e}, alpha={t1.alpha}")
print(f"Interpretation: {t1.interpretation}")
print(f"additional_params: {t1.additional_params}")

---
## 4. Preprocessing

Data quality reports, cleaning, transformations, outlier detection.

In [42]:
pp = Preprocessing(iris)
print(f"Backend: {pp.backend}")

Backend: Backend(type=pandas, shape=(150, 5))

### describe_numeric / describe_categorical

In [43]:
pp.describe_numeric()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [44]:
pp.describe_categorical()

       species
count      150
unique       3
top     setosa
freq        50

### Data Quality

In [45]:
pp.data_quality()

         column    dtype  nulls  null_pct  unique_values  completeness_pct
0  sepal_length  float64      0       0.0             35               1.0
1   sepal_width  float64      0       0.0             23               1.0
2  petal_length  float64      0       0.0             43               1.0
3   petal_width  float64      0       0.0             22               1.0
4       species   object      0       0.0              3               1.0

### Missing Values

In [46]:
pp.detect_nulls()

         column  nulls  non_nulls  null_pct
0  sepal_length      0        150       0.0
1   sepal_width      0        150       0.0
2  petal_length      0        150       0.0
3   petal_width      0        150       0.0
4       species      0        150       0.0

In [47]:
pp.fill_nulls(fill_with=0, columns=["sepal_length"])

### clean_data
Full cleaning pipeline: duplicates, missing, whitespace, dtype conversion.

In [48]:
pp_clean = Preprocessing(iris.copy())
pp_clean.clean_data(drop_duplicates=True, handle_missing="auto")
print(f"Shape after clean: {pp_clean.data.shape}")

Shape after clean: (147, 5)

### Preview & Uniqueness

In [49]:
pp.preview_data(n=3)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [50]:
pp.check_uniqueness()

         column  unique_values
0  sepal_length             35
1   sepal_width             23
2  petal_length             43
3   petal_width             22
4       species              3

### Normalization & Standardization

In [51]:
pp2 = Preprocessing(iris.copy())
pp2.normalize("sepal_length")
print(f"Normalized (0-1): min={pp2.data['sepal_length'].min():.2f}, max={pp2.data['sepal_length'].max():.2f}")

Normalized (0-1): min=0.00, max=1.00

In [52]:
pp3 = Preprocessing(iris.copy())
pp3.standardize("sepal_length")
print(f"Standardized (z): mean={pp3.data['sepal_length'].mean():.4f}, std={pp3.data['sepal_length'].std():.4f}")

Standardized (z): mean=-0.0000, std=1.0000

### Filtering & Renaming

In [53]:
pp4 = Preprocessing(iris.copy())
pp4.filter_columns(["sepal_length", "species"])
print(f"Filtered columns: {list(pp4.data.columns)}")

Filtered columns: ['sepal_length', 'species']

In [54]:
pp5 = Preprocessing(iris.copy())
pp5.filter_rows(pp5.data["sepal_length"] > 5.0)
print(f"Filtered rows: {pp5.data.shape[0]}")

Filtered rows: 118

In [55]:
pp6 = Preprocessing(iris.copy())
pp6.rename_columns({"sepal_length": "SL", "sepal_width": "SW"})
print(f"Renamed columns: {list(pp6.data.columns)}")

Renamed columns: ['SL', 'SW', 'petal_length', 'petal_width', 'species']

### Change DTypes & Outliers

In [56]:
pp7 = Preprocessing(iris.copy())
pp7.change_dtypes(columns=["species"], from_type="object", to_type="string")
print(f"Dtypes: {pp7.data.dtypes.to_dict()}")

In [57]:
pp7.detect_outliers(column="sepal_length", method="iqr")

No outliers found in column 'sepal_length'

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

---
## 5. ComputationalStats

Bootstrap, clustering, regression, interpolation, numerical methods.

In [58]:
cs = ComputationalStats(synth)
print(f"Backend: {cs.backend}")

Backend: Backend(type=pandas, shape=(1000, 7))

### Bootstrapping

In [59]:
boot = cs.bootstrapping("income", n_samples=500, statistic="mean")
bs = boot.summary()
print(f"Original stat: {bs['original_statistic']:.2f}")
print(f"Std error: {bs['std_error']:.4f}")
print(f"95% CI (percentile): {bs['confidence_interval_95%']['percentile']}")

In [ ]:
boot_med = cs.bootstrapping("income", n_samples=500, statistic="median")
print(boot_med.summary())

In [ ]:
# Custom statistic
boot_custom = cs.bootstrapping("income", n_samples=200, statistic="custom",
                                custom_func=lambda x: np.percentile(x, 90))
print(boot_custom.summary())

### K-Means Clustering

In [ ]:
kmeans = cs.k_means(k=3, max_iters=100)
print(f"Centroids shape: {kmeans['centroids'].shape}")
print(f"Inertia: {kmeans['inertia']:.2f}")
print(f"Silhouette: {kmeans['silhouette']:.4f}")

### Elbow Method

In [ ]:
elbow = cs.elbow_method(max_k=8)
print(f"Inertias: {elbow['inertias']}")

### Regression

In [ ]:
reg = cs.linear_regression(X=["age", "score"], y="income")
print(f"Regression R-squared: {reg.r_squared:.4f}")
print(f"Coefficients: {reg.coefficients}")

In [ ]:
poly = cs.polynomial_regression(X="age", y="income", degree=3)
print(f"Polynomial R-squared: {poly.r_squared:.4f}")

In [ ]:
reg2 = cs.regression(X=["age", "score"], y="income", degree=2, interaction_terms=True)
print(f"Regression (interactions): R-squared={reg2.r_squared:.4f}")

### Find Best Polynomial Degree

In [ ]:
best = cs.find_best_degree(X="age", y="income", max_degree=5, metric="r2")
print(f"Best degree: {best['best_degree']}")
print(f"Best R-squared: {best['best_metric']:.4f}")

### Interpolation

In [ ]:
points = [(0, 0), (1, 2), (2, 1), (3, 5)]
interp = cs.interpolation(points, method="lagrange")
print(f"Interpolation polynomial: {interp.polynomial}")
print(f"Value at x=1.5: {interp.evaluate(1.5):.4f}")

In [ ]:
interp2 = cs.interpolation(points, method="spline", spline_degree=3)
print(f"Spline value at x=1.5: {interp2.evaluate(1.5):.4f}")

### Correlation Analysis

In [ ]:
ca = cs.correlation_analysis(method="pearson")
print(f"Correlation matrix shape: {ca['correlation_matrix'].shape}")
print(ca['correlation_matrix'])

### Descriptive Statistics (grouped)

In [ ]:
cs.descriptive_statistics(by="group")

### Plotting

In [ ]:
cs.plot_correlation_heatmap(method="pearson", annot=True)

In [ ]:
cs.plot_distribution(column="age", by="group", kind="box")

### ComputationalStats.help()

In [ ]:
# cs.help()  # uncomment to display

### Result objects: RegressionResult, InterpolationResult, BootstrappingResult
Methods: `summary()`, `plot()`, `predict()` (regression/interpolation), `get_formula()` (regression).

In [ ]:
reg = cs.linear_regression(X="age", y="income")
print(reg.summary())
print(f"Formula: {reg.get_formula()}")
print(f"Predict age=40: {reg.predict([40])}")

In [ ]:
points = [(0, 0), (1, 2), (2, 1), (3, 5)]
interp = cs.interpolation(points, method="lagrange")
print(interp.summary())
print(f"Predict x=2.5: {interp.predict(2.5):.4f}")

---
## 6. UtilsStats

Utility class for loading, analyzing, and visualizing data.

In [ ]:
utils = UtilsStats()

### load_data
Load data from files (CSV, Excel, JSON, Parquet, Feather).

In [ ]:
# utils.load_data("data.csv")  # uncomment with actual file

### validate_dataframe
Convert various input types to a DataFrame.

In [ ]:
df_from_array = utils.validate_dataframe(np.array([[1, 2], [3, 4]]))
print(df_from_array)

### check_normality

In [ ]:
utils.check_normality(iris["sepal_length"], alpha=0.05)

### calculate_confidence_intervals

In [ ]:
utils.calculate_confidence_intervals(iris["sepal_length"], method="parametric")

In [ ]:
utils.calculate_confidence_intervals(iris["sepal_length"], method="bootstrap")

### detect_outliers
IQR, Z-score, and Isolation Forest methods.

In [ ]:
out = utils.detect_outliers(iris["sepal_length"], method="iqr")
print(f"IQR outliers: {out.sum()}")

In [ ]:
out2 = utils.detect_outliers(iris["sepal_length"], method="zscore", threshold=3)
print(f"Z-score outliers: {out2.sum()}")

In [ ]:
out3 = utils.detect_outliers(iris["sepal_length"], method="isolation_forest")
print(f"Isolation Forest outliers: {out3.sum()}")

### calculate_effect_size
Cohen's d or Hedges' g.

In [ ]:
setosa = iris[iris["species"] == "setosa"]["sepal_length"]
versicolor = iris[iris["species"] == "versicolor"]["sepal_length"]
utils.calculate_effect_size(group1=setosa, group2=versicolor, method="cohen")

In [ ]:
utils.calculate_effect_size(group1=setosa, group2=versicolor, method="hedges")

### format_number

In [ ]:
print(utils.format_number(3.1415926535, decimals=4))
print(utils.format_number(0.000123, decimals=2, scientific=True))

### get_descriptive_stats

In [ ]:
utils.get_descriptive_stats(iris, column="sepal_length")

In [ ]:
utils.get_descriptive_stats(iris, columns=["sepal_length", "petal_length"])

### Visualization: plot_distribution

In [ ]:
utils.plot_distribution(iris, column="sepal_length", plot_type="hist", bins=20)

In [ ]:
utils.plot_distribution(iris, column="sepal_length", plot_type="all")

In [ ]:
utils.plot_distribution(iris, column="species", plot_type="box")

### plot_correlation_matrix

In [ ]:
utils.plot_correlation_matrix(iris, method="pearson", triangular=True)

### plot_scatter_matrix

In [ ]:
utils.plot_scatter_matrix(iris, columns=["sepal_length", "sepal_width", "petal_length"])

### plot_distribution_with_ci

In [ ]:
utils.plot_distribution_with_ci(iris, column="sepal_length", confidence_level=0.95)

### Configuration Methods

In [ ]:
utils.set_plot_backend("seaborn")
utils.set_default_figsize((10, 4))
utils.set_save_fig_options(save_fig=False, fig_format="png", fig_dpi=300, figures_dir="figures")

### UtilsStats.help()

In [ ]:
# utils.help()  # uncomment to display

---
## 7. Backend Support

All major classes automatically detect **polars** DataFrames.

In [ ]:
try:
    import polars as pl
    pdf = pl.DataFrame({"x": [1.0, 2.0, 3.0], "y": [4.0, 5.0, 6.0], "z": ["a", "b", "c"]})
    ds_p = DescriptiveStats(pdf)
    print(f"Polars backend: {ds_p.backend}")
    print(f"Mean: {ds_p.mean('x')}")
except ImportError:
    print("Polars not installed - install with: pip install statslibx[polars]")

---
## 8. Command-Line Interface

Run from terminal (not the notebook):

In [ ]:
print("Terminal commands:")
print("  statslibx data iris.csv --summary")
print("  statslibx describe iris.csv --numeric")
print("  statslibx describe iris.csv --categorical")
print("  statslibx preview iris.csv -n 10")
print("  statslibx preview iris.csv -n 5 --sample")
print("  statslibx quality iris.csv --verbose")
print("  statslibx info iris.csv --detailed")
print("  statslibx --help")

---
## 9. Logging

StatsLibX uses Python's logging module.

In [ ]:
import logging
slx.logger.setLevel(logging.INFO)
ds_log = DescriptiveStats(iris)
ds_log.mean("sepal_length")
slx.logger.setLevel(logging.WARNING)

---
## 10. ViewX Integration

Visualization and reporting bridge (`statslibx.viewx`). Requires `pip install viewx`.

In [ ]:
try:
    from statslibx import HTML, Slides, Report, DataMatrix, to_report_data
    payload = to_report_data(ds.summary(columns=['sepal_length']))
    print(f"Report payload keys: {list(payload.keys())}")
    print(f"Title: {payload['title']}")
    print("ViewX classes available: HTML, Slides, Report, DataMatrix")
except ImportError as e:
    print(f"ViewX not installed: {e}")

### to_report_data
Serialize `DescriptiveSummary`, `TestResult`, or `RegressionResult` to a dict for ViewX reports.

In [ ]:
from statslibx.viewx.adapters import to_report_data

payload = to_report_data(inf.t_test_1sample('sepal_length', popmean=5.8))
print(payload)

---
## 11. Backend class

Low-level pandas/polars wrapper used internally by all domain classes.

In [ ]:
from statslibx.backend import Backend

be = Backend(iris)
print(be)
print(f"Numeric: {be.numeric_columns()}")
print(f"Mean sepal_length: {be.mean('sepal_length'):.4f}")
print(be.corr().round(3))

---
## 12. Package attributes

In [ ]:
print(f"Version: {slx.__version__}")
print(f"Author: {slx.__author__}")
print(f"Public exports: {slx.__all__}")